### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MarshalLeeeeee** [MarshalLeeeeee/SimFactory#1]
- [x] implement Renderdoc
- [x] add Renderdoc dll 
- [x] abstract Panel between ui and ui widget
- [x] decouple UI widget render and update
- [x] consider remove raw parent ptr
- [x] thread pool singleton
- [x] add logger singleton
- [x] async function (callback), control the speed of consuming task in main thread
- [x] async resource loader, 
- [x] resource cache: [care ref_cnt in async]
- [x] similarity transformation by shader
- [x] make pos, rot, scale basic property for model
- [x] refactor simentity renderentity and renderobj
- [x] introduce material class to encapsulate shader and shader buffers
- [x] create resource manager to save sharable vertex data, material data, etc
- [x] make vBuffer non access write
- [x] remove vBuffer data mapping
- [x] fix singleton copy and move function declaration
- [x] support string format in logger
